Allow setting controller block owner deletion false
nolar/kopf pull request #858
Opened 2021-11-01 19:23 UTC by nashant

## What do these changes do?

This will allow setting controller and blockOwnerDeletion from both build_owner_references and append_owner_references

## Description

Previous behaviour:
Error from trying to set multiple owner controllers

New behaviour:
Allow explicitly setting `controller=False`, so no error

Does the change affect end users?
Only if they choose to use it

## Issues/PRs

> Related:
https://github.com/nolar/kopf/issues/687

## Type of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] The code addresses only the mentioned problem, and this problem only
- [x] I think the code is well written
- [X] Unit tests for the changes exist
- [X] Documentation reflects the changes
- [X] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`

2021-11-02 08:02 UTC, nolar requested changes
Would it also make sense to add these same-named arguments to `kopf.adopt()` — an aggregate on top of all these ownership/hierarchy functions? For consistency of the interfaces. Wdyt?

2021-11-02 08:02 UTC, nolar commented on kopf/_cogs/structs/bodies.py
> +        block_owner_deletion: Optional[bool] = True,
Can you please make these arguments to be kwarg-only? As it is generally done for all "mode specifiers" in the public interface(s) — unlike for positional arguments which are typically the objects of the action, not its modes.

```suggestion
        *,
        controller: Optional[bool] = True,
        block_owner_deletion: Optional[bool] = True,
```

2021-11-02 08:02 UTC, nolar commented on kopf/_kits/hierarchies.py
> +        block_owner_deletion: Optional[bool] = True,
```suggestion
        *,
        controller: Optional[bool] = True,
        block_owner_deletion: Optional[bool] = True,
```

2021-11-02 08:54 UTC, nolar commented
Please rebase on `main` and force-push — #859 has fixed the tests.

2021-11-02 09:39 UTC, nashant commented
> Would it also make sense to add these same-named arguments to `kopf.adopt()` — an aggregate on top of all these ownership/hierarchy functions? For consistency of the interfaces. Wdyt?

I considered that and decided probably not. As per the comment you left on the issue I referenced I think adopt means that the child is under full control of the parent. If I'm adding an owner ref explicitly then I may well want to have multiple, if I'm adopting then I want that as the only owner

2021-11-02 09:59 UTC, nashant commented
I've rebased against main but am still getting the `tests/hierarchies/test_labelling.py` failures

2021-11-02 10:08 UTC, nashant commented
Ok, I've re-rebased against your main (forgot I had accidentally pushed to my main) and commits are now clean, but still the same test failures

2021-11-04 07:46 UTC, nashant commented
> > Would it also make sense to add these same-named arguments to `kopf.adopt()` — an aggregate on top of all these ownership/hierarchy functions? For consistency of the interfaces. Wdyt?
> 
> I considered that and decided probably not. As per the comment you left on the issue I referenced I think adopt means that the child is under full control of the parent. If I'm adding an owner ref explicitly then I may well want to have multiple, if I'm adopting then I want that as the only owner

@nolar what would you prefer?

2022-04-02 13:31 UTC, merged